//
// Created by guppy on 4/18/2026.
//

#pragma once
#include <string_view>
#include <vector>
#include <json/json.hpp>

using nlohmann::json;

namespace gp::network
{
    std::vector<uint8_t> Serialize(std::string_view string);
    std::vector<uint8_t> Serialize(const json& json);

    // Emitting should only allow values which have a Serialize() function for them!
    template <typename T>
    concept Serializable = requires(const T& t) { Serialize(t); };
    template <typename T>
    concept NetworkPacket = Serializable<T>; // || std::same_as<std::remove_cvref_t<T>, std::vector<uint8_t>>;
    // ^ this line was partially generated by chatGPT (specifically the std::remove_cvref_t<T> part)
    

    // NOTE: this returns a uint8_t* to the start of `value` so value must exist after this function is called! (also ik this is very C-like)
    template <typename T>
    const uint8_t* ToBytes(const T& value) // TODO: make sure this sends a certain endian type
    {
        return reinterpret_cast<const uint8_t*>(&value);
    }

    template <typename T>
    void AppendAsBytes(std::vector<uint8_t>& dest, const T& value)
    {
        auto bytes = ToBytes(value);
        dest.insert(dest.end(), bytes, bytes + sizeof(T));
    }
}
