//
// Created by guppy on 4/18/2026.
//

#pragma once
#include <string>
#include <string_view>
#include <vector>
#include <json/json.hpp>

using nlohmann::json;

namespace gp::network
{

    struct NetworkPacket
    {
        uint8_t type;
        std::string eventName;
        std::vector<uint8_t> data;
    };

    std::vector<uint8_t> Serialize(std::string_view string);
    std::vector<uint8_t> Serialize(const json& json);

    // Emitting should only allow values which have a Serialize() function for them!
    template <typename T>
    concept Serializable = requires(const T& t) { Serialize(t); };
    template <typename T>
    concept NetworkData = Serializable<T>; // || std::same_as<std::remove_cvref_t<T>, std::vector<uint8_t>>; // TODO: think about this so hard
    // ^ this line was partially generated by chatGPT (specifically the std::remove_cvref_t<T> part)
    

    // NOTE: this returns a uint8_t* to the start of `value` so value must exist after this function is called!
    template <typename T>
    const uint8_t* ToBytes(const T& value) // TODO: make sure this sends a certain endian type
    {
        return reinterpret_cast<const uint8_t*>(&value);
    }

    template <typename T>
    void AppendAsBytes(std::vector<uint8_t>& dest, const T& value)
    {
        auto bytes = ToBytes(value);
        dest.insert(dest.end(), bytes, bytes + sizeof(T));
    }

    std::vector<uint8_t> CreatePacket(std::string_view eventName, const std::vector<uint8_t>& data);

    NetworkPacket ParsePacket(const std::vector<uint8_t>& data);
    NetworkPacket ParsePacket(uint8_t type, int eventNameLength, int dataLength, const std::vector<uint8_t>& body);

    template <typename T>
    T ReadData(const std::vector<uint8_t>& data, int& offset)
    {
        if (data.size() < offset + sizeof(T)) throw std::runtime_error("Tried reading data bigger than buffer!");
        T value = 0;
        memcpy(&value, data.data() + offset, sizeof(T));
        offset += sizeof(T);
        return value;
    }

    // Note: this can cause an overflow! Please be careful you are reading something smaller than the buffer
    template <typename T>
    T ReadData(const uint8_t* data, const int offset = 0) // TODO: make readonly and non-readonly versions lowk
    {
        T value = 0;
        memcpy(&value, data + offset, sizeof(T));
        return value;
    }

}
